uname_s=`uname -s`
if [ "x$uname_s" == "xDarwin" ]; then
    export CLICOLORS=1
    export LSCOLORS="Exfxcxdxbxegedabagacad"
elif [ "x$uname_s" == "xFreeBSD" ]; then
    alias vi='vim'
else
    if [ -x /usr/bin/dircolors ]; then
        test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    fi
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi
